#include <iostream>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "./parser/ast.hh"
#include "./parser/parser.hh"

using namespace std;

extern int error_count;
extern bool yydebug;

bool print_ast = false;
bool type_check = true;
// TODO: add more flag variables

void usage(char *program_name) {
    cerr << "Usage:\n"
         << program_name << " [-flag(s)] <file>\n"
         << program_name << " [-h]\n"
         << "Options:\n"
         << "  -h: print this help message\n"
         << "  -a: print abstract syntax tree\n"
         << "  -c: disable type checking\n"
         << "  -y: print symbol table\n";
    // TODO: add more flags
    exit(1);
}

int main(int argc, char **argv) {
    char options[] = "acyh"; // TODO: add more flags
    int option;
    bool print_symtab = false;

    extern FILE *yyin;

    while ((option = getopt(argc, argv, options)) != EOF) {
        switch (option) { // TODO: add more flags
            case 'a':
                cout << "an AST will be printed for each block\n";
                print_ast = true;
                break;
            case 'c':
                cout << "no type checking will be performed\n";
                type_check = false;
                break;
            case 'y':
                cout << "symbol table will be printed after compilation\n";
                print_symtab = true;
                break;
            case 'h':
            default:
                usage(argv[0]);
                break;
        }
    }

    if (optind > argc || optind < argc - 1) {
        usage(argv[0]);
    }
    else if (optind == argc) {
        yyin = stdin;
    }
    else {
        yyin = fopen(argv[optind], "r");
        if (yyin == NULL) {
            perror(argv[optind]);
            exit(1);
        }
    }

    /*
    start compilation
    generated by bison from parser.y
    */
    yyparse();

    if(print_symtab) {
        sym_tab->print(2);
        sym_tab->print(1);
    }
    exit(error_count);
}