error.o: error.cc error.hh
scanner.o: scanner.cc scanner.hh symtab.hh error.hh
test.o: test.cc symtab.hh error.hh scanner.hh
symtab.o: symtab.cc symtab.hh error.hh
symbol.o: symbol.cc symtab.hh error.hh
