symbol.o: symbol.cc symtab.hh error.hh
symtab.o: symtab.cc symtab.hh error.hh
ast.o: parser/ast.cc parser/ast.hh parser/../symtab.hh parser/../error.hh
semantic.o: semantics/semantic.cc semantics/semantic.hh \
 semantics/../parser/ast.hh semantics/../parser/../symtab.hh \
 semantics/../parser/../error.hh
error.o: error.cc error.hh
main.o: main.cc
